services:
  nginx:
    image: nginx:1.28.0
    container_name: DACN-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-gateway
      - realtime-service
      - auth-service
      - storage-service
    networks:
      - backend
    restart: always

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: brookvita3/api-gateway:local
    container_name: DACN-api-gateway
    env_file:
      - ./api-gateway/.env
    environment:
      OCR_HTTP_URL: http://ocr-service:8010
    ports:
      - "5002:5002"
    depends_on:
      - auth-service
      - realtime-service
      - storage-service
      - ocr-service
    networks:
      - backend
    restart: always

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: brookvita3/auth-service:local
    container_name: DACN-auth-service
    env_file:
      - ./auth-service/.env
    ports:
      - "5000:5000"
    networks:
      - backend
    restart: always
    depends_on:
      timescaledb:
        condition: service_healthy
      storage-service:
        condition: service_started

  realtime-service:
    build:
      context: ./realtime-service
      dockerfile: Dockerfile
    image: brookvita3/realtime-service:local
    container_name: DACN-realtime-service
    env_file:
      - ./realtime-service/.env
    ports:
      - "5001:5001"
    restart: on-failure
    depends_on:
      timescaledb:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - backend

  storage-service:
    build:
      context: ./storage-service
      dockerfile: Dockerfile
    image: brookvita3/storage-service:local
    container_name: DACN-storage-service
    env_file:
      - ./storage-service/.env
    ports:
      - "5003:5003"
    networks:
      - backend
    depends_on:
      timescaledb:
        condition: service_healthy
      kafka:
        condition: service_healthy

  ocr-service:
    build:
      context: ./ocr-service
      dockerfile: Dockerfile
    image: brookvita3/ocr-service:local
    container_name: DACN-ocr-service
    env_file:
      - ./ocr-service/.env
    ports:
      - "8010:8010"
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 2G

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v25.1.4
    container_name: DACN-redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    networks:
      - backend
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - 8081:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
    volumes:
      - ./kafka/kui/config.yml:/etc/kafkaui/dynamic_config.yaml
    depends_on:
      - redpanda
    networks:
      - backend

  timescaledb:
    image: timescale/timescaledb:2.19.3-pg14
    container_name: DACN1-timescaledb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: healthmate
    volumes:
      - timescaledbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"] 
      interval: 6s 
      timeout: 6s
      retries: 6 

  redis:
    image: redis:8.2.0
    container_name: DACN1-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  timescaledbdata:
    driver: local
  redisdata:
    driver: local
  zookeeper_data:
    driver: local
  zookeeper_log:
    driver: local
  kafka_data:
    driver: local
