// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	medication "storage-service/internal/medication"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MedicationRepository is an autogenerated mock type for the Repository type
type MedicationRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, med
func (_m *MedicationRepository) Create(ctx context.Context, med *medication.Medication) error {
	ret := _m.Called(ctx, med)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *medication.Medication) error); ok {
		r0 = rf(ctx, med)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateShare provides a mock function with given fields: ctx, share
func (_m *MedicationRepository) CreateShare(ctx context.Context, share *medication.MedicationShare) error {
	ret := _m.Called(ctx, share)

	if len(ret) == 0 {
		panic("no return value specified for CreateShare")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *medication.MedicationShare) error); ok {
		r0 = rf(ctx, share)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, medicationID, userID
func (_m *MedicationRepository) Delete(ctx context.Context, medicationID string, userID string) error {
	ret := _m.Called(ctx, medicationID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, medicationID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteShare provides a mock function with given fields: ctx, shareID, medicationID, userID
func (_m *MedicationRepository) DeleteShare(ctx context.Context, shareID string, medicationID string, userID string) error {
	ret := _m.Called(ctx, shareID, medicationID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteShare")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, shareID, medicationID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMissedRemindersToNotify provides a mock function with given fields: ctx, now
func (_m *MedicationRepository) GetMissedRemindersToNotify(ctx context.Context, now time.Time) ([]medication.MissedReminderNotification, error) {
	ret := _m.Called(ctx, now)

	if len(ret) == 0 {
		panic("no return value specified for GetMissedRemindersToNotify")
	}

	var r0 []medication.MissedReminderNotification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]medication.MissedReminderNotification, error)); ok {
		return rf(ctx, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []medication.MissedReminderNotification); ok {
		r0 = rf(ctx, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]medication.MissedReminderNotification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRemindersToTrigger provides a mock function with given fields: ctx
func (_m *MedicationRepository) GetRemindersToTrigger(ctx context.Context) ([]medication.MedicationReminder, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRemindersToTrigger")
	}

	var r0 []medication.MedicationReminder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]medication.MedicationReminder, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []medication.MedicationReminder); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]medication.MedicationReminder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByUserID provides a mock function with given fields: ctx, userID
func (_m *MedicationRepository) ListByUserID(ctx context.Context, userID string) ([]medication.Medication, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []medication.Medication
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]medication.Medication, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []medication.Medication); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]medication.Medication)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListShares provides a mock function with given fields: ctx, medicationID
func (_m *MedicationRepository) ListShares(ctx context.Context, medicationID string) ([]medication.MedicationShare, error) {
	ret := _m.Called(ctx, medicationID)

	if len(ret) == 0 {
		panic("no return value specified for ListShares")
	}

	var r0 []medication.MedicationShare
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]medication.MedicationShare, error)); ok {
		return rf(ctx, medicationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []medication.MedicationShare); ok {
		r0 = rf(ctx, medicationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]medication.MedicationShare)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, medicationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ToggleTake provides a mock function with given fields: ctx, medicationID, reminderID, userID
func (_m *MedicationRepository) ToggleTake(ctx context.Context, medicationID string, reminderID string, userID string) error {
	ret := _m.Called(ctx, medicationID, reminderID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ToggleTake")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, medicationID, reminderID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateShareNotificationStatus provides a mock function with given fields: ctx, shareID, reminderID, notifiedDate
func (_m *MedicationRepository) UpdateShareNotificationStatus(ctx context.Context, shareID string, reminderID string, notifiedDate time.Time) error {
	ret := _m.Called(ctx, shareID, reminderID, notifiedDate)

	if len(ret) == 0 {
		panic("no return value specified for UpdateShareNotificationStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) error); ok {
		r0 = rf(ctx, shareID, reminderID, notifiedDate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMedicationRepository creates a new instance of MedicationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMedicationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MedicationRepository {
	mock := &MedicationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
