// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	metric "storage-service/internal/metric"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MetricRepository is an autogenerated mock type for the MetricRepository type
type MetricRepository struct {
	mock.Mock
}

// CheckAccess provides a mock function with given fields: ctx, observerID, targetID, metricType
func (_m *MetricRepository) CheckAccess(ctx context.Context, observerID string, targetID string, metricType string) (bool, error) {
	ret := _m.Called(ctx, observerID, targetID, metricType)

	if len(ret) == 0 {
		panic("no return value specified for CheckAccess")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (bool, error)); ok {
		return rf(ctx, observerID, targetID, metricType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) bool); ok {
		r0 = rf(ctx, observerID, targetID, metricType)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, observerID, targetID, metricType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAggregatedMetrics provides a mock function with given fields: ctx, userID, metricType, bucketSize, startTime, endTime
func (_m *MetricRepository) GetAggregatedMetrics(ctx context.Context, userID string, metricType string, bucketSize string, startTime time.Time, endTime time.Time) ([]metric.MetricDataPoint, error) {
	ret := _m.Called(ctx, userID, metricType, bucketSize, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for GetAggregatedMetrics")
	}

	var r0 []metric.MetricDataPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, time.Time, time.Time) ([]metric.MetricDataPoint, error)); ok {
		return rf(ctx, userID, metricType, bucketSize, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, time.Time, time.Time) []metric.MetricDataPoint); ok {
		r0 = rf(ctx, userID, metricType, bucketSize, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]metric.MetricDataPoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, userID, metricType, bucketSize, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMetricWatchers provides a mock function with given fields: ctx, userID, metricType
func (_m *MetricRepository) GetMetricWatchers(ctx context.Context, userID string, metricType string) ([]metric.Watcher, error) {
	ret := _m.Called(ctx, userID, metricType)

	if len(ret) == 0 {
		panic("no return value specified for GetMetricWatchers")
	}

	var r0 []metric.Watcher
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]metric.Watcher, error)); ok {
		return rf(ctx, userID, metricType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []metric.Watcher); ok {
		r0 = rf(ctx, userID, metricType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]metric.Watcher)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, metricType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetThresholdByMetricName provides a mock function with given fields: ctx, userID, metricName
func (_m *MetricRepository) GetThresholdByMetricName(ctx context.Context, userID string, metricName string) (*metric.UserThreshold, error) {
	ret := _m.Called(ctx, userID, metricName)

	if len(ret) == 0 {
		panic("no return value specified for GetThresholdByMetricName")
	}

	var r0 *metric.UserThreshold
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*metric.UserThreshold, error)); ok {
		return rf(ctx, userID, metricName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *metric.UserThreshold); ok {
		r0 = rf(ctx, userID, metricName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metric.UserThreshold)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, metricName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserName provides a mock function with given fields: ctx, userID
func (_m *MetricRepository) GetUserName(ctx context.Context, userID string) (string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserName")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserThresholds provides a mock function with given fields: ctx, userID
func (_m *MetricRepository) GetUserThresholds(ctx context.Context, userID string) ([]metric.UserThreshold, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserThresholds")
	}

	var r0 []metric.UserThreshold
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]metric.UserThreshold, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []metric.UserThreshold); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]metric.UserThreshold)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, _a1
func (_m *MetricRepository) Store(ctx context.Context, _a1 *metric.HealthMetric) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *metric.HealthMetric) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertThreshold provides a mock function with given fields: ctx, threshold
func (_m *MetricRepository) UpsertThreshold(ctx context.Context, threshold *metric.UserThreshold) error {
	ret := _m.Called(ctx, threshold)

	if len(ret) == 0 {
		panic("no return value specified for UpsertThreshold")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *metric.UserThreshold) error); ok {
		r0 = rf(ctx, threshold)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMetricRepository creates a new instance of MetricRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricRepository {
	mock := &MetricRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
