// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	notification "storage-service/internal/notification"

	mock "github.com/stretchr/testify/mock"
)

// NotificationService is an autogenerated mock type for the Service type
type NotificationService struct {
	mock.Mock
}

// SendToToken provides a mock function with given fields: ctx, token, _a2
func (_m *NotificationService) SendToToken(ctx context.Context, token string, _a2 notification.Notification) error {
	ret := _m.Called(ctx, token, _a2)

	if len(ret) == 0 {
		panic("no return value specified for SendToToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, notification.Notification) error); ok {
		r0 = rf(ctx, token, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendToUser provides a mock function with given fields: ctx, userID, _a2
func (_m *NotificationService) SendToUser(ctx context.Context, userID string, _a2 notification.Notification) error {
	ret := _m.Called(ctx, userID, _a2)

	if len(ret) == 0 {
		panic("no return value specified for SendToUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, notification.Notification) error); ok {
		r0 = rf(ctx, userID, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationService creates a new instance of NotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationService {
	mock := &NotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
