// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "healthmate/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// GoogleTokenVerifier is an autogenerated mock type for the GoogleTokenVerifier type
type GoogleTokenVerifier struct {
	mock.Mock
}

// VerifyGoogleIDToken provides a mock function with given fields: ctx, idToken
func (_m *GoogleTokenVerifier) VerifyGoogleIDToken(ctx context.Context, idToken string) (*domain.GoogleUser, error) {
	ret := _m.Called(ctx, idToken)

	if len(ret) == 0 {
		panic("no return value specified for VerifyGoogleIDToken")
	}

	var r0 *domain.GoogleUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.GoogleUser, error)); ok {
		return rf(ctx, idToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.GoogleUser); ok {
		r0 = rf(ctx, idToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GoogleUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, idToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGoogleTokenVerifier creates a new instance of GoogleTokenVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGoogleTokenVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *GoogleTokenVerifier {
	mock := &GoogleTokenVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
