// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "auth-service/internal/domain"
	group "auth-service/internal/group"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// GroupRepository is an autogenerated mock type for the GroupRepository type
type GroupRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, params
func (_m *GroupRepository) Create(ctx context.Context, params group.CreateGroupParams) (*domain.Group, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, group.CreateGroupParams) (*domain.Group, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, group.CreateGroupParams) *domain.Group); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, group.CreateGroupParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *GroupRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: ctx, id
func (_m *GroupRepository) Exists(ctx context.Context, id uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *GroupRepository) FindByID(ctx context.Context, id uuid.UUID) (*domain.Group, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Group, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Group); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByNameAndOwner provides a mock function with given fields: ctx, name, ownerID
func (_m *GroupRepository) FindByNameAndOwner(ctx context.Context, name string, ownerID uuid.UUID) (*domain.Group, error) {
	ret := _m.Called(ctx, name, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for FindByNameAndOwner")
	}

	var r0 *domain.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) (*domain.Group, error)); ok {
		return rf(ctx, name, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) *domain.Group); ok {
		r0 = rf(ctx, name, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = rf(ctx, name, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByOwner provides a mock function with given fields: ctx, ownerID, limit, offset
func (_m *GroupRepository) FindByOwner(ctx context.Context, ownerID uuid.UUID, limit int, offset int) ([]domain.Group, error) {
	ret := _m.Called(ctx, ownerID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindByOwner")
	}

	var r0 []domain.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]domain.Group, error)); ok {
		return rf(ctx, ownerID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []domain.Group); ok {
		r0 = rf(ctx, ownerID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, ownerID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUser provides a mock function with given fields: ctx, userID, limit, offset
func (_m *GroupRepository) FindByUser(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]domain.Group, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindByUser")
	}

	var r0 []domain.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]domain.Group, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []domain.Group); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, params
func (_m *GroupRepository) List(ctx context.Context, params group.ListGroupsParams) ([]domain.Group, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, group.ListGroupsParams) ([]domain.Group, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, group.ListGroupsParams) []domain.Group); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, group.ListGroupsParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransferOwnership provides a mock function with given fields: ctx, groupID, newOwnerID
func (_m *GroupRepository) TransferOwnership(ctx context.Context, groupID uuid.UUID, newOwnerID uuid.UUID) error {
	ret := _m.Called(ctx, groupID, newOwnerID)

	if len(ret) == 0 {
		panic("no return value specified for TransferOwnership")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, groupID, newOwnerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, id, params
func (_m *GroupRepository) Update(ctx context.Context, id uuid.UUID, params group.UpdateGroupParams) error {
	ret := _m.Called(ctx, id, params)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, group.UpdateGroupParams) error); ok {
		r0 = rf(ctx, id, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewGroupRepository creates a new instance of GroupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGroupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *GroupRepository {
	mock := &GroupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
