// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "auth-service/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MemberRepository is an autogenerated mock type for the MemberRepository type
type MemberRepository struct {
	mock.Mock
}

// AddMember provides a mock function with given fields: ctx, groupID, userID, invitedBy, role
func (_m *MemberRepository) AddMember(ctx context.Context, groupID uuid.UUID, userID uuid.UUID, invitedBy uuid.UUID, role string) error {
	ret := _m.Called(ctx, groupID, userID, invitedBy, role)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, groupID, userID, invitedBy, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMember provides a mock function with given fields: ctx, groupID, userID
func (_m *MemberRepository) GetMember(ctx context.Context, groupID uuid.UUID, userID uuid.UUID) (*domain.GroupMember, error) {
	ret := _m.Called(ctx, groupID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMember")
	}

	var r0 *domain.GroupMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.GroupMember, error)); ok {
		return rf(ctx, groupID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.GroupMember); ok {
		r0 = rf(ctx, groupID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GroupMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, groupID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListGroupMembers provides a mock function with given fields: ctx, groupID
func (_m *MemberRepository) ListGroupMembers(ctx context.Context, groupID uuid.UUID) ([]domain.GroupMember, error) {
	ret := _m.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for ListGroupMembers")
	}

	var r0 []domain.GroupMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.GroupMember, error)); ok {
		return rf(ctx, groupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.GroupMember); ok {
		r0 = rf(ctx, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.GroupMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveMember provides a mock function with given fields: ctx, groupID, userID
func (_m *MemberRepository) RemoveMember(ctx context.Context, groupID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, groupID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, groupID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateMemberStatus provides a mock function with given fields: ctx, groupID, userID, status
func (_m *MemberRepository) UpdateMemberStatus(ctx context.Context, groupID uuid.UUID, userID uuid.UUID, status string) error {
	ret := _m.Called(ctx, groupID, userID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMemberStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, groupID, userID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMemberRepository creates a new instance of MemberRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMemberRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MemberRepository {
	mock := &MemberRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
