// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "auth-service/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PermissionRepository is an autogenerated mock type for the PermissionRepository type
type PermissionRepository struct {
	mock.Mock
}

// ListUserPermissionsInGroup provides a mock function with given fields: ctx, groupID, userID
func (_m *PermissionRepository) ListUserPermissionsInGroup(ctx context.Context, groupID uuid.UUID, userID uuid.UUID) ([]domain.Permission, error) {
	ret := _m.Called(ctx, groupID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserPermissionsInGroup")
	}

	var r0 []domain.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]domain.Permission, error)); ok {
		return rf(ctx, groupID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []domain.Permission); ok {
		r0 = rf(ctx, groupID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, groupID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RevokePermission provides a mock function with given fields: ctx, groupID, userID, metricType
func (_m *PermissionRepository) RevokePermission(ctx context.Context, groupID uuid.UUID, userID uuid.UUID, metricType string) error {
	ret := _m.Called(ctx, groupID, userID, metricType)

	if len(ret) == 0 {
		panic("no return value specified for RevokePermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, groupID, userID, metricType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetPermission provides a mock function with given fields: ctx, groupID, userID, metricType
func (_m *PermissionRepository) SetPermission(ctx context.Context, groupID uuid.UUID, userID uuid.UUID, metricType string) error {
	ret := _m.Called(ctx, groupID, userID, metricType)

	if len(ret) == 0 {
		panic("no return value specified for SetPermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, groupID, userID, metricType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPermissionRepository creates a new instance of PermissionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPermissionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PermissionRepository {
	mock := &PermissionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
