// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "auth-service/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PermissionRepository is an autogenerated mock type for the PermissionRepository type
type PermissionRepository struct {
	mock.Mock
}

// IsMember provides a mock function with given fields: ctx, groupID, userID
func (_m *PermissionRepository) IsMember(ctx context.Context, groupID uuid.UUID, userID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, groupID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsMember")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, groupID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, groupID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, groupID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsValidMetricType provides a mock function with given fields: ctx, metricType
func (_m *PermissionRepository) IsValidMetricType(ctx context.Context, metricType string) (bool, error) {
	ret := _m.Called(ctx, metricType)

	if len(ret) == 0 {
		panic("no return value specified for IsValidMetricType")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, metricType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, metricType)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, metricType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListMetricTypes provides a mock function with given fields: ctx
func (_m *PermissionRepository) ListMetricTypes(ctx context.Context) ([]domain.MetricType, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListMetricTypes")
	}

	var r0 []domain.MetricType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.MetricType, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.MetricType); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MetricType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUserPermissionsInGroup provides a mock function with given fields: ctx, groupID, userID
func (_m *PermissionRepository) ListUserPermissionsInGroup(ctx context.Context, groupID uuid.UUID, userID uuid.UUID) ([]domain.Permission, error) {
	ret := _m.Called(ctx, groupID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserPermissionsInGroup")
	}

	var r0 []domain.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]domain.Permission, error)); ok {
		return rf(ctx, groupID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []domain.Permission); ok {
		r0 = rf(ctx, groupID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, groupID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RevokeAllPermissions provides a mock function with given fields: ctx, groupID, userID
func (_m *PermissionRepository) RevokeAllPermissions(ctx context.Context, groupID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, groupID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllPermissions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, groupID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokePermission provides a mock function with given fields: ctx, groupID, userID, metricType
func (_m *PermissionRepository) RevokePermission(ctx context.Context, groupID uuid.UUID, userID uuid.UUID, metricType string) error {
	ret := _m.Called(ctx, groupID, userID, metricType)

	if len(ret) == 0 {
		panic("no return value specified for RevokePermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, groupID, userID, metricType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetPermission provides a mock function with given fields: ctx, groupID, userID, metricType
func (_m *PermissionRepository) SetPermission(ctx context.Context, groupID uuid.UUID, userID uuid.UUID, metricType string) error {
	ret := _m.Called(ctx, groupID, userID, metricType)

	if len(ret) == 0 {
		panic("no return value specified for SetPermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = rf(ctx, groupID, userID, metricType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPermissionRepository creates a new instance of PermissionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPermissionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PermissionRepository {
	mock := &PermissionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
