// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "auth-service/internal/domain"
	group "auth-service/internal/group"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateGroup provides a mock function with given fields: ctx, ownerID, name, description
func (_m *Service) CreateGroup(ctx context.Context, ownerID uuid.UUID, name string, description *string) (*domain.Group, error) {
	ret := _m.Called(ctx, ownerID, name, description)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroup")
	}

	var r0 *domain.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, *string) (*domain.Group, error)); ok {
		return rf(ctx, ownerID, name, description)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, *string) *domain.Group); ok {
		r0 = rf(ctx, ownerID, name, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, *string) error); ok {
		r1 = rf(ctx, ownerID, name, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteGroup provides a mock function with given fields: ctx, groupID, requesterID
func (_m *Service) DeleteGroup(ctx context.Context, groupID uuid.UUID, requesterID uuid.UUID) error {
	ret := _m.Called(ctx, groupID, requesterID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, groupID, requesterID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetGroup provides a mock function with given fields: ctx, groupID
func (_m *Service) GetGroup(ctx context.Context, groupID uuid.UUID) (*domain.Group, error) {
	ret := _m.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroup")
	}

	var r0 *domain.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Group, error)); ok {
		return rf(ctx, groupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Group); ok {
		r0 = rf(ctx, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsGroupOwner provides a mock function with given fields: ctx, groupID, userID
func (_m *Service) IsGroupOwner(ctx context.Context, groupID uuid.UUID, userID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, groupID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsGroupOwner")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, groupID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, groupID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, groupID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListGroups provides a mock function with given fields: ctx, params
func (_m *Service) ListGroups(ctx context.Context, params group.ListGroupsParams) ([]domain.Group, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListGroups")
	}

	var r0 []domain.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, group.ListGroupsParams) ([]domain.Group, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, group.ListGroupsParams) []domain.Group); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, group.ListGroupsParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUserGroups provides a mock function with given fields: ctx, userID, limit, offset
func (_m *Service) ListUserGroups(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]domain.Group, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListUserGroups")
	}

	var r0 []domain.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]domain.Group, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []domain.Group); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransferOwnership provides a mock function with given fields: ctx, groupID, currentOwnerID, newOwnerID
func (_m *Service) TransferOwnership(ctx context.Context, groupID uuid.UUID, currentOwnerID uuid.UUID, newOwnerID uuid.UUID) error {
	ret := _m.Called(ctx, groupID, currentOwnerID, newOwnerID)

	if len(ret) == 0 {
		panic("no return value specified for TransferOwnership")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, groupID, currentOwnerID, newOwnerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateGroup provides a mock function with given fields: ctx, groupID, name, description, requesterID
func (_m *Service) UpdateGroup(ctx context.Context, groupID uuid.UUID, name *string, description *string, requesterID uuid.UUID) error {
	ret := _m.Called(ctx, groupID, name, description, requesterID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string, *string, uuid.UUID) error); ok {
		r0 = rf(ctx, groupID, name, description, requesterID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
