// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// EmailService is an autogenerated mock type for the EmailService type
type EmailService struct {
	mock.Mock
}

// ResendOTP provides a mock function with given fields: ctx, recipientEmail, recipientName, otp
func (_m *EmailService) ResendOTP(ctx context.Context, recipientEmail string, recipientName string, otp string) error {
	ret := _m.Called(ctx, recipientEmail, recipientName, otp)

	if len(ret) == 0 {
		panic("no return value specified for ResendOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, recipientEmail, recipientName, otp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendOTP provides a mock function with given fields: ctx, recipientEmail, recipientName, otp
func (_m *EmailService) SendOTP(ctx context.Context, recipientEmail string, recipientName string, otp string) error {
	ret := _m.Called(ctx, recipientEmail, recipientName, otp)

	if len(ret) == 0 {
		panic("no return value specified for SendOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, recipientEmail, recipientName, otp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendWelcomeEmail provides a mock function with given fields: ctx, recipientEmail, recipientName
func (_m *EmailService) SendWelcomeEmail(ctx context.Context, recipientEmail string, recipientName string) error {
	ret := _m.Called(ctx, recipientEmail, recipientName)

	if len(ret) == 0 {
		panic("no return value specified for SendWelcomeEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, recipientEmail, recipientName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEmailService creates a new instance of EmailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailService(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailService {
	mock := &EmailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
