ALTER TABLE users
DROP COLUMN IF EXISTS phone,
DROP COLUMN IF EXISTS address,
DROP COLUMN IF EXISTS gender,
DROP COLUMN IF EXISTS birthday,
DROP COLUMN IF EXISTS weight,
DROP COLUMN IF EXISTS height,
DROP COLUMN IF EXISTS blood_group;
