basePath: /
host: localhost:5001
info:
  contact: {}
  description: This is the API for Realtime Service of HealthMate application.
  title: HealthMate Realtime API
  version: "1.0"
paths:
  /ws:
    get:
      description: Upgrade to WebSocket connection for real-time metrics
      parameters:
      - description: Authentication token
        in: query
        name: token
        required: true
        type: string
      responses:
        "101":
          description: Switching Protocols
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: Webhook connection
      tags:
      - realtime
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    description: Token should be passed as a query parameter for WebSocket connection.
    in: query
    name: token
    type: apiKey
swagger: "2.0"
