name: CI/CD api-gateway on EC2

on:
  push:
    branches: [ "main" ]
    paths:
      - "api-gateway/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "api-gateway/**"
      - ".github/workflows/api-gateway.yml"

jobs:
  ci:
    name: CI - Test Golang
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: api-gateway

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

  cd:
    name: CD - Deploy to EC2
    needs: ci
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./api-gateway
          file: ./api-gateway/Dockerfile
          push: true
          tags: |
            brookvita3/api-gateway:${{ github.sha }}

      - name: SSH to EC2 & deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull brookvita3/api-gateway:${{ github.sha }}
            docker stop api-gateway || true
            docker rm api-gateway || true
            docker run -d \
              --name api-gateway \
              -p 80:8080 \
              --restart unless-stopped \
              brookvita3/api-gateway:${{ github.sha }}
